### ISSUE TITLE
Error when initialising Sensor on OH 4.2.0

### ISSUE THREAD

**Issue by sbushnell** [seime/openhab-fyta#7]
Hi, 

The sensors do go on line briefly and appears when its retrieving the sensor data it fails with
HANDLER_INITIALIZING_ERROR
'void org.openhab.core.library.types.DecimalType.<init>(double)'

I havent do any traces as I thought the below error is common due to changes from OH3 to OH4? Happy to send traces if needed.

Thanks
Scott

**Comment by sbushnell** [comment]
Thought would make easier to get trace

2024-08-08 10:55:15.020 [ERROR] [nal.common.AbstractInvocationHandler] - An error occurred while calling method 'ThingHandler.initialize()' on 'no.seime.openhab.binding.fyta.internal.handler.FytaPlantHandler@1c76971f': 'void org.openhab.core.library.types.DecimalType.<init>(double)'
java.lang.NoSuchMethodError: 'void org.openhab.core.library.types.DecimalType.<init>(double)'
	at no.seime.openhab.binding.fyta.internal.handler.FytaPlantHandler.updateChannel(FytaPlantHandler.java:255) ~[?:?]
	at no.seime.openhab.binding.fyta.internal.handler.FytaPlantHandler.lambda$3(FytaPlantHandler.java:157) ~[?:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at no.seime.openhab.binding.fyta.internal.handler.FytaPlantHandler.loadPlantDetails(FytaPlantHandler.java:157) ~[?:?]
	at no.seime.openhab.binding.fyta.internal.handler.FytaPlantHandler.initialize(FytaPlantHandler.java:95) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:147) [bundleFile:?]
	at org.openhab.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]

**Comment by seime** [comment]
Are you running the latest 4.x version from the marketplace? I'm running 4.1.3, and just tested with 4.2.0. Works fine.

https://github.com/seime/openhab-fyta/releases/tag/latest_oh4

**Comment by sbushnell** [comment]
Hi,

OK, I got this error because it couldn't retrieve the data I think? The hub
was noy connected to the sensors. Now OK.

Thanks for your quick reply and excellent Binding😁

**Comment by seime** [comment]
Cool, happy to support you :)

https://github.com/seime/support-me
